version: '3.4'

services:
  web:
    build: .
    container_name: ${PROJECT_NAME:-project}-web
    volumes:
      - .:/var/www
      - ./docker-entry.sh:/etc/entrypoint.sh
    entrypoint: [ "sh", "/etc/entrypoint.sh" ]
    env_file:
      - ../envs/.env-${GITHUB_REPOSITORY_NAME}
    environment:
      APP_PORT: 3310
      APP_SECRET: 123456789
      FRONTEND_URL: "https://${PROJECT_NAME}.${HOST}"
      VITE_BACKEND_URL: "https://${PROJECT_NAME}.${HOST}:3310"
      DB_HOST: database-db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${PROJECT_NAME:-project}-secure.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME:-project}-secure.rule=Host(`${PROJECT_NAME:-project}.${HOST:-localhost}`)"
      - "traefik.http.services.${PROJECT_NAME:-project}.loadbalancer.server.port=3310"

networks:
  proxy:
    external: true
